version: "3.8"

services:
  app:
    build: .
    container_name: image-classification-api
    expose:
      - "5000"
    volumes:
      - .:/app
      - ./model:/app/model

  nginx:
    image: nginx:alpine
    container_name: nginx-proxy
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app

networks:
  default:
    name: app-network
