version: "3.8"

services:
  classification_app:
    build: .
    hostname: classification
    ports:
      - "5000:5000"
    volumes:
      - .:/app
      - ./model:/app/model
    networks:
      - main_network

networks:
  main_network:
    external: true
